#!/usr/bin/env bash

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
# ignore-cmd
# ==========
# Add paths to .gitignore & .npmignore from cmd
#
#!/usr/bin/env bash

function ignore () {
	local flag="$1"
	shift

	while (( "$#" )) ; do
		if [ "$flag" = '-g' ] ; then
			echo "$1" >> "$PWD/.gitignore"
		elif [ "$flag" = '-n' ] ; then
			echo "$1" >> "$PWD/.npmignore"
		else
			echo "$1" >> "$PWD/.gitignore"
			echo "$1" >> "$PWD/.npmignore"
		fi

		shift
	done 
}

function help () {
	echo 'Usage:    ignore <flag> <path> [...paths] '
	echo
	echo '    flag      -g  add to .gitignore'
	echo '              -n  add to .npmignore'
	echo '              -b  add to both'
	echo
	echo '    path       The path you want to ignore (e.g. /node_modules/)'
	echo
	echo '    paths      Ignore multiple paths'
	echo
}

function die () {
	echo "$*"
	kill -INT $$
}



if [ "$#" -lt 2 ] ; then
	help && die
fi


case "$1" in
        -g|-n|-b)
			flag="$1"
			shift
			paths="$@"
			;;
        *)
			help && die
			;;
esac

ignore $flag $paths

# unset variables
unset flag
unset paths
